###
Get http://localhost:5000
###

# ----------------------------- Invalid URL ------------------------------

###
Get http://localhost:5000/hi
###

###
Get http://localhost:5000/hi/nodejs
###

###
Get http://localhost:5000/err
###

# ----------------------------- END Invalid URL ------------------------------

###
Get http://localhost:5000/api/v1/basic01
###

###
Get http://localhost:5000/api/v1/basic01/express
###

###
Get http://localhost:5000/api/v1/basic01/err
###

###
Get http://localhost:5000/api/v1/basic01/err2
###

###
Get http://localhost:5000/api/v1/blogs
###

###
POST http://localhost:5000/api/v1/blogs
Content-Type: application/json

{
    "title" : "Test 1"
}
###

###
POST http://localhost:5000/api/v1/blogs
Content-Type: application/json

{
    "title" : "Test 2"
}
###